version: '3'

services:

  mongo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./mongod.conf:/etc/mongod.conf
      - ./mongodb:/data/db
      - ./mongodb:/data/configdb
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    tty: true
    networks:
      - tchx

networks:
  tchx:
  proxy:
    external: true

